name: 'stitchery'

services:
    frontend:
        build:
            context: ./stitchery-frontend
            target: dev
        restart: unless-stopped
        environment:
            - FRONTEND_PORT
            - API_PORT
        ports:
            - "${FRONTEND_PORT:-8080}:${FRONTEND_PORT:-8080}"
        volumes:
            - ./stitchery-frontend:/app:cached

    api:
        build:
            context: ./stitchery-api
            target: dev
        restart: unless-stopped
        environment:
            - API_PORT
            - APOLLO_KEY
            - APOLLO_GRAPH_REF
            - APOLLO_SCHEMA_REPORTING
            - DB_CONNECTION_LIMIT
            - DB_URI_SCHEME
            - DB_CREDENTIALS_FILE=/run/secrets/$DB_CREDENTIALS_FILE
            - JWT_SECRET_FILE=/run/secrets/$JWT_SECRET_FILE
        ports:
            - "${API_PORT:-3000}:${API_PORT:-3000}"
        volumes:
            - ./stitchery-api:/app:cached
        secrets:
            - db-credentials
            - jwt-secret

    db:
        build: ./stitchery-db
        restart: unless-stopped
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -d stitchery -U stitchery" ]
            interval: 10s
            timeout: 3s
            retries: 3
        volumes:
            - db-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        secrets:
            - db-credentials

    pg-admin:
        image: dpage/pgadmin4:latest
        restart: unless-stopped
        environment:
            - PGADMIN_DEFAULT_EMAIL
            - PGADMIN_DEFAULT_PASSWORD_FILE=/run/secrets/pg-admin-password
        volumes:
            - pg-admin-data:/var/lib/pgadmin
            - "${CONFIG_DIR}/pgadmin4/config_local.py:/pgadmin4/config_local.py:ro"
            - "${CONFIG_DIR}/pgadmin4/servers.json:/pgadmin4/servers.json:ro"
        secrets:
            - pg-admin-password

    nginx:
        image: nginx:latest
        restart: unless-stopped
        environment:
            - APP_DOMAIN
        ports:
            - 80:80
            - 443:443
        depends_on:
            - frontend
            - api
            - db
            - certbot
        volumes:
            - "${CONFIG_DIR}/nginx/templates:/etc/nginx/templates:ro"
            - "${CONFIG_DIR}/nginx/docker-entrypoint.d/autoreload.sh:/docker-entrypoint.d/autoreload.sh:ro"
            - "${CONFIG_DIR}/nginx/ssl:/etc/nginx/ssl:ro"
            - "${CONFIG_DIR}/letsencrypt:/etc/letsencrypt:ro"
            - "${CONFIG_DIR}/certbot/www:/var/www/certbot:ro"

    certbot:
        image: certbot/certbot:latest
        restart: unless-stopped
        volumes:
            - "${CONFIG_DIR}/letsencrypt:/etc/letsencrypt"
            - "${CONFIG_DIR}/certbot/www:/var/www/certbot"
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
    db-data:
    pg-admin-data:


secrets:
    db-credentials:
        file: "${SECRETS_DIR}${DB_CREDENTIALS_FILE}"
    jwt-secret:
        file: "${SECRETS_DIR}${JWT_SECRET_FILE}"
    pg-admin-password:
        file: "${SECRETS_DIR}${PGADMIN_PASSWORD_FILE}"
